### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by saadyousuf45** [Ikomia-hub/train_mmlab_detection#3]
RuntimeError: Algorithm infer_mmlab_detection is installed locally but not functional. Check your code or your Python environment please.

I get this error when i run code in python.

**Comment by saadyousuf45** [comment]
>>> from ikomia.core import IODataType
/media/saadi/Drive/Thesis_Folder/Thesis_2022/HPC_codes/ikomia/lib/python3.8/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/media/saadi/Drive/Thesis_Folder/Thesis_2022/HPC_codes/ikomia/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/media/saadi/Drive/Thesis_Folder/Thesis_2022/HPC_codes/ikomia/lib/python3.8/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/media/saadi/Drive/Thesis_Folder/Thesis_2022/HPC_codes/ikomia/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
>>> from ikomia.dataprocess.workflow import Workflow
>>> from ikomia.utils.displayIO import display
>>> wf = Workflow()
>>> detector = wf.add_task(name="infer_mmlab_detection", auto_connect=True)
Traceback (most recent call last):
  File "/media/saadi/Drive/Thesis_Folder/Thesis_2022/HPC_codes/ikomia/lib/python3.8/site-packages/ikomia/dataprocess/registry.py", line 161, in create_algorithm
    self._load_algorithm(name, algo_dir, language)
  File "/media/saadi/Drive/Thesis_Folder/Thesis_2022/HPC_codes/ikomia/lib/python3.8/site-packages/ikomia/dataprocess/registry.py", line 321, in _load_algorithm
    self.load_python_algorithm(directory)
RuntimeError: Algorithm infer_mmlab_detection could not be loaded:<class 'ModuleNotFoundError'>: No module named 'panopticapi':   File "/home/saadi/Ikomia/Plugins/Python/infer_mmlab_detection/infer_mmlab_detection_process.py", line 26, in <module>
    from panopticapi.utils import rgb2id
 (Code 9)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/saadi/Drive/Thesis_Folder/Thesis_2022/HPC_codes/ikomia/lib/python3.8/site-packages/ikomia/dataprocess/workflow.py", line 277, in add_task
    task = self.registry.create_algorithm(name=name,
  File "/media/saadi/Drive/Thesis_Folder/Thesis_2022/HPC_codes/ikomia/lib/python3.8/site-packages/ikomia/dataprocess/registry.py", line 174, in create_algorithm
    raise RuntimeError(f"Algorithm {name} is installed locally but not functional. "
RuntimeError: Algorithm infer_mmlab_detection is installed locally but not functional. Check your code or your Python environment please.
